### ISSUE TITLE
Facing typeError issue while using upstash lock

### ISSUE THREAD

**Issue by shishirkj** [upstash/lock#9]
## Problem:

I'm creating a chatapp where a user calls an api which  returns a roomId ,but i was facing a problem where if two users call that api at same time which i dont want to happen as it leads to race condition,to solve i had used upstash lock but facing type error
<img width="1109" alt="Screenshot 2024-03-28 221904" src="https://github.com/upstash/lock/assets/90249481/34b15efa-62d3-4b0a-b875-b2a43f7f881f">

# component calling the api
```




 const Room = ({params}:roomProps) => {
    const {userId}= params
    const [roomId,setRoomId] = useState();
   

    async function getRoomId() {
      const API_BASE_URL =
   process.env.NEXT_PUBLIC_MODE === "production"? "https://blinkchat-nu.vercel.app": "http://localhost:3000";
  
      try {
        const { data } = await axios.get(
          `${API_BASE_URL}/api/roomIdExists/${userId}`
        );
        const value =await data.mssg;
        setRoomId(value);
      
      } catch (error) {
        console.error("Error fetching roomId:", error);
        setRoomId(undefined); // Reset roomId on error
      }
    }
    
    

 
//USING UPSTASH LOCK HERE
   useEffect(() => {
    async function fixRaceCondtion(){ 
      //since two browsers were hitting this api at same time it was causing race condition
  //to prevent that we are using lock system from redis

    const lock = new Lock({
      id:`userId`,
      lease: 2000,
      redis:client,
    });

console.log("console log",lock)

    if(await lock.acquire())
    {
       getRoomId();
       await lock.release()
      }
      else{ 
          console.log("lock not acquired")
      }
  }

  fixRaceCondtion()
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [userId]);
    
 

    if (roomId === undefined) {
      return <div>Loading...</div>;
    }
  
 
```

**Comment by MeshanKhosla** [comment]
Hi, thanks for making an issue. The issue you're running into is because you are attempting to use this library on the cilent side, which is not allowed. `@upstash/lock` is intended to be used on the server (ie: an API endpoint or server component if using Nextjs). If you move this code to the server, it'll behave as expected.

For your use case, the lock should be acquired on the server in the case of multiple clients trying to connect to it, and having it on the client won't solve the issue. Also, it's a security concern to create the lock on the client side because it exposes your Redis credentials to anyone using the app.

Let me know if you have any questions!
